In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [4]:
df= pd.read_csv('/content/student3.csv')
df.columns

Index(['roll', 'name', 'class', 'marks ', 'age'], dtype='object')

In [5]:
df.columns = df.columns.str.strip()#the strip method is permantly used to remove space
#before and after the string
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [6]:
df['marks'].mean()

66.96714285714286

In [7]:
df['class'].value_counts()# this will give me mode or occurance of each particular class

TE    9
BE    4
be    2
Name: class, dtype: int64

In [8]:
#here you can see small letter 'be'
# now to convert all df['class'] values to upper case
df['class']=df['class'].str.upper()
df['class'].value_counts()

TE    9
BE    6
Name: class, dtype: int64

In [9]:
df['name']=df['name'].str.title()
df['name']

0        Anil
1        Amit
2      Aniket
3     Ajinkya
4        Asha
5      Ayesha
6        Amar
7       Amita
8        Amol
9        Amol
10      Anmol
11     Surbhi
12      Sujay
13    Subhash
14     Sachin
15    Shalini
Name: name, dtype: object

In [10]:
# to identify the duplicate entires
df.duplicated()
print(df)

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
4      5     Asha    TE  63.28   NaN
5      6   Ayesha    BE    NaN  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    BE  68.33  23.0
8      9     Amol    TE  56.75  20.0
9      9     Amol    TE  56.75  20.0
10    10    Anmol    BE  78.66   NaN
11    11   Surbhi    TE    NaN  23.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    BE  88.45  21.0
14    14   Sachin   NaN  59.33  21.0
15    15  Shalini    TE  63.45  20.0

In [11]:
# to drop duplicates
df.drop_duplicates(inplace = True)

In [14]:
#To count non_ null values in the dataset
print(df.count())

roll     15
name     15
class    14
marks    13
age      13
dtype: int64

In [17]:
#we can use df.isNull()
#it will return true where data is NULL or NaN

df.isnull()

     roll   name  class  marks    age
0   False  False  False  False  False
1   False  False  False  False  False
2   False  False  False  False  False
3   False  False  False  False  False
4   False  False  False  False   True
5   False  False  False   True  False
6   False  False  False  False  False
7   False  False  False  False  False
8   False  False  False  False  False
10  False  False  False  False   True
11  False  False  False   True  False
12  False  False  False  False  False
13  False  False  False  False  False
14  False  False   True  False  False
15  False  False  False  False  False

In [18]:
True+True

2

In [19]:
True+False

1

In [22]:
df.isnull().sum()
# this will

roll     0
name     0
class    1
marks    2
age      2
dtype: int64

In [24]:
#to work with missing values
#when we use the dropna() function we get on an averge 10% data loss
df.dropna()

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    BE  68.33  23.0
8      9     Amol    TE  56.75  20.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    BE  88.45  21.0
15    15  Shalini    TE  63.45  20.0

In [26]:
#we can replace the value the value in NaN
#fillna() function will replace the values in the null space in that particular column
# we have to work for each column
# we cannot use the fillna() function for entire dataframe at once.
df['marks'].fillna(60)

0     56.77
1     59.77
2     76.88
3     69.66
4     63.28
5     60.00
6     65.34
7     68.33
8     56.75
10    78.66
11    60.00
12    74.12
13    88.45
14    59.33
15    63.45
Name: marks, dtype: float64

In [29]:
#we can replace the values based on the type of the data
# if the values are discrete we can replace it with the median value
# if the values are continous then we replace it with average value.

#here the marks are continous
df.fillna(df['marks'].mean())

    roll     name      class      marks        age
0      1     Anil         TE  56.770000  22.000000
1      2     Amit         TE  59.770000  21.000000
2      3   Aniket         BE  76.880000  19.000000
3      4  Ajinkya         TE  69.660000  20.000000
4      5     Asha         TE  63.280000  67.753077
5      6   Ayesha         BE  67.753077  20.000000
6      7     Amar         BE  65.340000  19.000000
7      8    Amita         BE  68.330000  23.000000
8      9     Amol         TE  56.750000  20.000000
10    10    Anmol         BE  78.660000  67.753077
11    11   Surbhi         TE  67.753077  23.000000
12    12    Sujay         TE  74.120000  22.000000
13    13  Subhash         BE  88.450000  21.000000
14    14   Sachin  67.753077  59.330000  21.000000
15    15  Shalini         TE  63.450000  20.000000

In [31]:
#here  the values are discrete hence we replace the values here with median
df['age'].fillna(df['age'].median())

0     22.0
1     21.0
2     19.0
3     20.0
4     21.0
5     20.0
6     19.0
7     23.0
8     20.0
10    21.0
11    23.0
12    22.0
13    21.0
14    21.0
15    20.0
Name: age, dtype: float64

In [35]:
df['class'].mode()#this will give the most frequent value
#then we will replace this value in the categorical data

0    TE
Name: class, dtype: object

In [38]:
df['class'].fillna(df['class'].mode()[0])

0     TE
1     TE
2     BE
3     TE
4     TE
5     BE
6     BE
7     BE
8     TE
10    BE
11    TE
12    TE
13    BE
14    TE
15    TE
Name: class, dtype: object

In [40]:
#we can also replace the previous value in the NaN
#this can be done by ffill() function- Forward Fill method.
#we also have bfill() function.#by this we can Fill the NaN value with the previous record.
df.ffill()

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
4      5     Asha    TE  63.28  20.0
5      6   Ayesha    BE  63.28  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    BE  68.33  23.0
8      9     Amol    TE  56.75  20.0
10    10    Anmol    BE  78.66  20.0
11    11   Surbhi    TE  78.66  23.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    BE  88.45  21.0
14    14   Sachin    BE  59.33  21.0
15    15  Shalini    TE  63.45  20.0